INSERT INTO cardapios(data_servico, prato_principal, guarnicoes, bloqueado) VALUES('2026-01-05', 'BIFE BOVINO COM CEBOLA E TOMATE', 'CREME DE MILHO, ALFACE/TOMATE', 0);
INSERT INTO cardapios(data_servico, prato_principal, guarnicoes, bloqueado) VALUES('2026-01-06', 'SOBRECOXA DESOSSADA FRITA', 'BRÓCOLIS AO MOLHO BRANCO, BETERRABA', 0);
INSERT INTO cardapios(data_servico, prato_principal, guarnicoes, bloqueado) VALUES('2026-01-07', 'LINGUIÇA TOSCANA', 'BATATA RUSTICA ASSADA, ALFACE/TOMATE', 0);
INSERT INTO cardapios(data_servico, prato_principal, guarnicoes, bloqueado) VALUES('2026-01-08', 'COSTELINHA E FEIJÃO TROPEIRO', 'BATATA FRITA E SALADA MIX DE FOLHAS', 0);
INSERT INTO cardapios(data_servico, prato_principal, guarnicoes, bloqueado) VALUES('2026-01-09', 'FILÉ DE PEIXE FRITO (TILÁPIA)', 'FAROFA DE BACON E CENOURA, ALMEIRÃO/TOMATE', 0);
INSERT INTO cardapios(data_servico, prato_principal, guarnicoes, bloqueado) VALUES('2026-01-12', 'QUIBE ASSADO', 'COUVE NA MANTEIGA, SALADA DE BETERRABA', 0);
INSERT INTO cardapios(data_servico, prato_principal, guarnicoes, bloqueado) VALUES('2026-01-13', 'ESTROGONOFE DE FRANGO', 'FAROFA DE BACON E CENOURA, ALFACE/TOMATE', 0);
INSERT INTO cardapios(data_servico, prato_principal, guarnicoes, bloqueado) VALUES('2026-01-14', 'BIFE BOVINO COM CEBOLA E TOMATE', 'ABÓBORA CABOTIÁ, SALADA DE FOLHAS', 0);
INSERT INTO cardapios(data_servico, prato_principal, guarnicoes, bloqueado) VALUES('2026-01-15', 'ALMÔNDEGAS', 'MACARRÃO ALHO, AZEITE, BACON, ALFACE/TOMATE', 0);
INSERT INTO cardapios(data_servico, prato_principal, guarnicoes, bloqueado) VALUES('2026-01-16', 'CARNE DE PANELA', 'LEGUMES SAUTÊ TUTU DE FEIJÃO, CHICÓRIA', 0);
INSERT INTO cardapios(data_servico, prato_principal, guarnicoes, bloqueado) VALUES('2026-01-19', 'BIFE BOVINO COM CEBOLA E TOMATE, ', 'PURÊ DE BATATA, SALADA BETERRABA', 0);
INSERT INTO cardapios(data_servico, prato_principal, guarnicoes, bloqueado) VALUES('2026-01-20', 'ALMÔNDEGAS', 'MACARRÃO PIZZA, SALADA ALFACE', 0);
INSERT INTO cardapios(data_servico, prato_principal, guarnicoes, bloqueado) VALUES('2026-01-21', 'FILÉ DE PEIXE FRITO (TILÁPIA)', 'MIX DE LEGUMES, ESCAROLA/CENOURA', 0);
INSERT INTO cardapios(data_servico, prato_principal, guarnicoes, bloqueado) VALUES('2026-01-22', 'SOBRECOXA DESOSSADA FRITA', 'POLENTA AO MOLHO COM MUSSARELA, MIX DE FOLHAS', 0);
INSERT INTO cardapios(data_servico, prato_principal, guarnicoes, bloqueado) VALUES('2026-01-23', 'PARMEGIANA DE FRANGO', 'MACARRÃO AO ALHO, AZEITE, BACON, ALFACE/TOMATE', 0);
INSERT INTO cardapios(data_servico, prato_principal, guarnicoes, bloqueado) VALUES('2026-01-26', 'CARNE DE PANELA', 'BATATA AO MOLHO COM TOMATE, ALFACE/TOMATE', 0);
INSERT INTO cardapios(data_servico, prato_principal, guarnicoes, bloqueado) VALUES('2026-01-27', 'BIFE DE PERNIL ACEBOLADO', 'COUVE NA MANTEIGA, BETERRABA EM RODELAS', 0);
INSERT INTO cardapios(data_servico, prato_principal, guarnicoes, bloqueado) VALUES('2026-01-28', 'ESTROGONOFE DE FRANGO', 'FAROFA DE CENOURA E BACON, SALADA DE FOLHAS', 0);
INSERT INTO cardapios(data_servico, prato_principal, guarnicoes, bloqueado) VALUES('2026-01-29', 'CARNE MOÍDA', 'LASANHA, CHICÓRIA', 0);
INSERT INTO cardapios(data_servico, prato_principal, guarnicoes, bloqueado) VALUES('2026-01-30', 'COSTELINHA SUÍNA E TUTU DE FEIJÃO', 'COUVE NA MANTEIGA, SALADA VINAGRETE', 0);
